/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class feeReceipt extends javax.swing.JInternalFrame {

    /**
     * Creates new form feeReceipt
     */
    public feeReceipt() {
        initComponents();
           
        try
 {
 String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);
            
 
 try
 {
 String a="select * from feetable where admno=?";
 PreparedStatement mystatement=myconnection.prepareStatement(a);
 mystatement.setString(1, FeesManagement.adbox.getText());

 ResultSet myresult=mystatement.executeQuery();
 DefaultTableModel mymodel=(DefaultTableModel) frtable.getModel();
 String adm,c,s,t,f,d;
 if(myresult.next())
 {
 do
 {
 adm=myresult.getString("admno");
 c=myresult.getString("term");
 s=myresult.getString("mode");
 t=myresult.getString("totalfee");
 f=myresult.getString("paid");
 d=myresult.getString("due");
 mymodel.addRow(new String[]{adm,t,f,c,s,d});
 }
 while(myresult.next());
 }
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        frtable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Fees Receipt");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("FEE RECEIPT");

        frtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admission Number", "Total Fee", "Fee Paid", "Term", "Mode", "Due "
            }
        ));
        jScrollPane1.setViewportView(frtable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable frtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
