/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class FeesManagement extends javax.swing.JInternalFrame implements Printable {

    /**
     * Creates new form FeesManagement
     */
    public FeesManagement() {
        initComponents();
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        adbox = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        phn = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        ln = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        termbox2 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        cheque2 = new javax.swing.JRadioButton();
        cash2 = new javax.swing.JRadioButton();
        due2 = new javax.swing.JLabel();
        classbox6 = new javax.swing.JComboBox<>();
        sectionbox2 = new javax.swing.JComboBox<>();
        paidbox2 = new javax.swing.JFormattedTextField();
        jButton12 = new javax.swing.JButton();
        totalfee = new javax.swing.JLabel();
        dueAmount = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Fees Management");

        jLabel28.setText("Search by Admission number");

        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel29.setText("Father's Name");

        jLabel30.setText("Mother's Name");

        jLabel31.setText("Class");

        jLabel32.setText("Section ");

        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10jButton4ActionPerformed(evt);
            }
        });

        jButton11.setText("View Receipt");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setText("Phone Number");

        phn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel17.setText("Landline Number");

        ln.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel11.setText("Total Fees");

        jLabel33.setText("Paid");

        termbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Term", "1st Term", "2nd Term" }));
        termbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termbox2ActionPerformed(evt);
            }
        });

        jLabel35.setText("Mode Of Payment");

        buttonGroup1.add(cheque2);
        cheque2.setText("Cheque");

        buttonGroup1.add(cash2);
        cash2.setText("Cash");

        due2.setText("0");

        classbox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        classbox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbox6classbox2ActionPerformed(evt);
            }
        });

        sectionbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section", "A", "B", "C", "D" }));
        sectionbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionbox2sectionboxActionPerformed(evt);
            }
        });

        paidbox2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        paidbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidbox2paidboxActionPerformed(evt);
            }
        });

        jButton12.setText("Print Receipt");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        totalfee.setText("0");

        dueAmount.setText("Due Amount");
        dueAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adbox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(189, 189, 189))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fn)
                                    .addComponent(classbox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jButton9)
                            .addComponent(jLabel32)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sectionbox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                .addComponent(mn, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(343, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jButton10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton12))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel11))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(totalfee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(termbox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addComponent(paidbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cheque2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cash2)
                                    .addGap(434, 434, 434)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dueAmount)
                                .addGap(29, 29, 29)
                                .addComponent(due2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 284, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fn)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mn))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(classbox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sectionbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(phn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalfee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(termbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cheque2)
                    .addComponent(cash2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(due2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueAmount))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try {
                String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);

                try {
                    String a = "select * from studenttable where admno=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(a);
                    mystatement.setString(1, adbox.getText());
                    
                    ResultSet myresult = mystatement.executeQuery();
                    if (myresult.next()){
                       
                        
                    fn.setText(myresult.getString("fathername"));
                    mn.setText(myresult.getString("mothername"));
                     classbox6.setSelectedItem(myresult.getString("class"));
                        sectionbox2.setSelectedItem(myresult.getString("section"));
                        phn.setText(myresult.getString("phone"));
                         ln.setText(myresult.getString("landline"));
                    }
                     } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                } finally {
                    myconnection.close();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
        
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10jButton4ActionPerformed
        try
        {
             String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);
            try
            {
                String a="insert into feetable values(?,?,?,?,?,?)";
                PreparedStatement mystatement=myconnection.prepareStatement(a);
 mystatement.setString(1, adbox.getText());
                mystatement.setString(2, totalfee.getText());
                mystatement.setString(3, paidbox2.getText());
                
                
                
                
                mystatement.setString(6, due2.getText());
                mystatement.setString(4, termbox2.getSelectedItem().toString());

               
                if(cheque2.isSelected())
                {
                    mystatement.setString(5, "cheque");
                }
                else if(cash2.isSelected())
                {
                    mystatement.setString(5, "cash");
                }

                if(mystatement.executeUpdate()>0)
                {   adbox.setText("");
                    totalfee.setText("");
                    paidbox2.setText("");
                    due2.setText("");
                    fn.setText("");
                    mn.setText("");
                    phn.setText("");
                    ln.setText("");
                    classbox6.setSelectedIndex(0);
                        sectionbox2.setSelectedIndex(0);
                    termbox2.setSelectedIndex(0);
                    buttonGroup1.clearSelection();
                    JOptionPane.showMessageDialog(rootPane, "Fee Data Saved Successfully");
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton10jButton4ActionPerformed

    private void jButton11jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11jButton5ActionPerformed
feeReceipt obj=new feeReceipt();
HeadLogin.jDesktopPane1.add(obj);
       obj.setVisible(true); 
    }//GEN-LAST:event_jButton11jButton5ActionPerformed

    private void classbox6classbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbox6classbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classbox6classbox2ActionPerformed

    private void sectionbox2sectionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionbox2sectionboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionbox2sectionboxActionPerformed

    private void paidbox2paidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidbox2paidboxActionPerformed
         
    }//GEN-LAST:event_paidbox2paidboxActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
MessageFormat headerobj=new MessageFormat("Fee Receipt");
MessageFormat footerobj=new MessageFormat("Page(0)");
try{
feeReceipt.frtable.print(JTable.PrintMode.FIT_WIDTH,headerobj,footerobj);

}
catch(Exception e){
JOptionPane.showMessageDialog(rootPane,"Error in Printing due to"+ e.getMessage());
}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void dueAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueAmountActionPerformed
        int paid,total,due;
        paid=Integer.parseInt(paidbox2.getText());
        total=Integer.parseInt(totalfee.getText());
        due=total-paid;
        
     due2.setText(String.valueOf(due));    // TODO add your handling code here:
    }//GEN-LAST:event_dueAmountActionPerformed

    private void termbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termbox2ActionPerformed
        if(termbox2.getSelectedIndex()==1){
totalfee.setText("50000");


}
else if(termbox2.getSelectedIndex()==2){
totalfee.setText("35000");
}
    }//GEN-LAST:event_termbox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField adbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cash2;
    private javax.swing.JRadioButton cheque2;
    public static javax.swing.JComboBox<String> classbox6;
    private javax.swing.JLabel due2;
    private javax.swing.JButton dueAmount;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JFormattedTextField ln;
    private javax.swing.JTextField mn;
    private javax.swing.JFormattedTextField paidbox2;
    private javax.swing.JFormattedTextField phn;
    private javax.swing.JComboBox<String> sectionbox2;
    private javax.swing.JComboBox<String> termbox2;
    private javax.swing.JLabel totalfee;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
