/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author HP
 */
public class StudentManagement extends javax.swing.JInternalFrame {
int admno1,admdisplay1;
    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
      
        try {
                String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection2 = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);
try{

String query="select * from studenttable ";

 PreparedStatement mystatement2 = myconnection2.prepareStatement(query);
  ResultSet myresult2 = mystatement2.executeQuery();
  if(myresult2.next()){
       if(myresult2.last())
  
  
  {
admno1=Integer.parseInt(myresult2.getString("admno"));
admdisplay1=admno1+1;

jLabel2.setText(String.valueOf(admdisplay1));
  }
  }
}
     catch(Exception e){
         
         e.printStackTrace();
         
         
     }finally{
myconnection2.close();
}
         
         } catch(Exception e){
         e.printStackTrace();
         }  
        
    }
    File myfile;
    String imagename2;
 int admno,admdisplay;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        adbox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnamebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lnamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fatherbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        motherbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        malebtn = new javax.swing.JRadioButton();
        femalebtn = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        classbox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        sectionbox = new javax.swing.JComboBox<>();
        imagebox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        phonebox = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        landlinebox = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressbox = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        foccubox = new javax.swing.JComboBox<>();
        moccubox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bgbox = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        religionbox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        nbtn = new javax.swing.JRadioButton();
        adbtn = new javax.swing.JRadioButton();
        search = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        fathername = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        mothername = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ibox = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        phone = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        landline = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel41 = new javax.swing.JLabel();
        foccu = new javax.swing.JComboBox<>();
        moccu = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        religion = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        classbox3 = new javax.swing.JComboBox<>();
        sectionbox1 = new javax.swing.JComboBox<>();
        admbox1 = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        fnamebox1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        lnamebox1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        fatherbox1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        motherbox1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        malebtn1 = new javax.swing.JRadioButton();
        femalebtn1 = new javax.swing.JRadioButton();
        jLabel52 = new javax.swing.JLabel();
        classbox1 = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        sectionbox2 = new javax.swing.JComboBox<>();
        imagebox1 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        phonebox1 = new javax.swing.JFormattedTextField();
        jLabel55 = new javax.swing.JLabel();
        landlinebox1 = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressbox1 = new javax.swing.JTextArea();
        jLabel57 = new javax.swing.JLabel();
        foccubox1 = new javax.swing.JComboBox<>();
        moccubox1 = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        bgbox1 = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        religionbox1 = new javax.swing.JComboBox<>();
        admbox2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        fnamebox2 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        lnamebox2 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        fatherbox2 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        motherbox2 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        malebtn2 = new javax.swing.JRadioButton();
        femalebtn2 = new javax.swing.JRadioButton();
        jLabel69 = new javax.swing.JLabel();
        classbox2 = new javax.swing.JComboBox<>();
        jLabel70 = new javax.swing.JLabel();
        sectionbox3 = new javax.swing.JComboBox<>();
        imagebox2 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        phonebox2 = new javax.swing.JFormattedTextField();
        jLabel72 = new javax.swing.JLabel();
        landlinebox2 = new javax.swing.JFormattedTextField();
        jButton11 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressbox2 = new javax.swing.JTextArea();
        jLabel74 = new javax.swing.JLabel();
        foccubox2 = new javax.swing.JComboBox<>();
        moccubox2 = new javax.swing.JComboBox<>();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        bgbox2 = new javax.swing.JComboBox<>();
        jLabel77 = new javax.swing.JLabel();
        religionbox2 = new javax.swing.JComboBox<>();
        admbox3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Student Management");

        jLabel1.setText("Admission Number");

        jLabel3.setText("First Name");

        fnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name");

        jLabel5.setText("Father's Name");

        jLabel6.setText("Mother's Name");

        jLabel8.setText("Gender");

        buttonGroup2.add(malebtn);
        malebtn.setText("Male");

        buttonGroup2.add(femalebtn);
        femalebtn.setText("Female");

        jLabel9.setText("Class");

        classbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        classbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classboxActionPerformed(evt);
            }
        });

        jLabel10.setText("Section");

        sectionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section", "A", "B", "C", "D" }));
        sectionbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionboxActionPerformed(evt);
            }
        });

        imagebox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Upload Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Phone Number");

        phonebox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel13.setText("Landline Number");

        landlinebox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Address");

        addressbox.setColumns(20);
        addressbox.setRows(5);
        addressbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addressboxMouseExited(evt);
            }
        });
        addressbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressboxKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(addressbox);

        jLabel15.setText("Father's Occupation");

        foccubox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));

        moccubox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));

        jLabel16.setText("Mother's Occupation");

        jLabel17.setText("Blood Group");

        bgbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel26.setText("Religion");

        religionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Religion", "Hindu", "Sikh", "Muslim", "Christian", "Jain", "Budhism", "Others" }));

        jLabel2.setText("1");

        javax.swing.GroupLayout adboxLayout = new javax.swing.GroupLayout(adbox);
        adbox.setLayout(adboxLayout);
        adboxLayout.setHorizontalGroup(
            adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adboxLayout.createSequentialGroup()
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(landlinebox))
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(phonebox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(classbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bgbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(religionbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adboxLayout.createSequentialGroup()
                                        .addComponent(malebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(adboxLayout.createSequentialGroup()
                                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fnamebox, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(fatherbox, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(foccubox, 0, 155, Short.MAX_VALUE))
                                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(adboxLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(adboxLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(adboxLayout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adboxLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(adboxLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(motherbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(moccubox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(168, 168, 168)
                                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imagebox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        adboxLayout.setVerticalGroup(
            adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adboxLayout.createSequentialGroup()
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addComponent(fnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(fatherbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(foccubox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moccubox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(malebtn)
                                    .addComponent(femalebtn))
                                .addGap(15, 15, 15)
                                .addComponent(classbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adboxLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(motherbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)))
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adboxLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(imagebox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)))
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(phonebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(bgbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adboxLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13))
                            .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(landlinebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26))))
                    .addGroup(adboxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(religionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(adboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admissions", jPanel1);

        jLabel25.setText("Search by");

        buttonGroup1.add(nbtn);
        nbtn.setText("Name");

        buttonGroup1.add(adbtn);
        adbtn.setText("Admission Number");
        adbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbtnActionPerformed(evt);
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel6.setLayout(null);

        jLabel27.setText("Admission Number");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(20, 0, 107, 16);

        jLabel28.setText("Admission Date");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(745, 3, 88, 16);

        jLabel29.setText("First Name");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(20, 31, 87, 16);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel6.add(fname);
        fname.setBounds(141, 31, 218, 22);

        jLabel30.setText("Last Name");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(439, 31, 98, 20);
        jPanel6.add(lname);
        lname.setBounds(578, 31, 122, 22);

        jLabel31.setText("Father's Name");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(20, 62, 83, 16);
        jPanel6.add(fathername);
        fathername.setBounds(141, 62, 218, 22);

        jLabel32.setText("Mother's Name");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(439, 62, 98, 16);
        jPanel6.add(mothername);
        mothername.setBounds(578, 62, 122, 22);

        jLabel33.setText("DOB");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(20, 124, 24, 24);

        jLabel34.setText("Gender");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(439, 125, 98, 23);

        male.setText("Male");
        jPanel6.add(male);
        male.setBounds(578, 125, 61, 25);

        female.setText("Female");
        jPanel6.add(female);
        female.setBounds(641, 125, 71, 25);

        jLabel35.setText("Class");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(20, 159, 30, 20);

        jLabel36.setText("Section");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(439, 159, 98, 20);

        ibox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(ibox);
        ibox.setBounds(836, 31, 130, 130);

        jLabel38.setText("Phone Number");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(20, 193, 84, 16);

        phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel6.add(phone);
        phone.setBounds(141, 190, 218, 22);

        jLabel39.setText("Landline Number");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(20, 224, 96, 16);

        landline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel6.add(landline);
        landline.setBounds(141, 221, 218, 22);

        jLabel40.setText("Address");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(20, 259, 46, 16);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(141, 259, 559, 96);

        jLabel41.setText("Father's Occupation");
        jPanel6.add(jLabel41);
        jLabel41.setBounds(20, 96, 120, 16);

        foccu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        jPanel6.add(foccu);
        foccu.setBounds(141, 93, 218, 22);

        moccu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        jPanel6.add(moccu);
        moccu.setBounds(578, 93, 122, 22);

        jLabel42.setText("Mother's Occupation");
        jPanel6.add(jLabel42);
        jLabel42.setBounds(439, 96, 116, 16);

        jLabel43.setText("Blood Group");
        jPanel6.add(jLabel43);
        jLabel43.setBounds(439, 193, 98, 16);

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel6.add(bg);
        bg.setBounds(578, 190, 142, 22);

        jLabel44.setText("Religion");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(439, 224, 98, 16);

        religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Religion", "Hindu", "Sikh", "Muslim", "Christian", "Jain", "Budhism", "Others" }));
        jPanel6.add(religion);
        religion.setBounds(578, 221, 122, 22);

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(139, 366, 73, 25);

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(216, 366, 69, 25);

        classbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class" }));
        classbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbox3ActionPerformed(evt);
            }
        });
        jPanel6.add(classbox3);
        classbox3.setBounds(141, 159, 218, 22);

        sectionbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section" }));
        sectionbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionbox1ActionPerformed(evt);
            }
        });
        jPanel6.add(sectionbox1);
        sectionbox1.setBounds(578, 159, 122, 22);
        jPanel6.add(admbox1);
        admbox1.setBounds(141, 0, 218, 22);

        jPanel7.setLayout(null);

        jLabel37.setText("Admission Number");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(0, 11, 120, 16);

        jLabel45.setText("Admission Date");
        jPanel7.add(jLabel45);
        jLabel45.setBounds(700, 10, 110, 20);

        jLabel46.setText("First Name");
        jPanel7.add(jLabel46);
        jLabel46.setBounds(0, 37, 96, 20);

        fnamebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamebox1ActionPerformed(evt);
            }
        });
        jPanel7.add(fnamebox1);
        fnamebox1.setBounds(154, 40, 155, 22);

        jLabel47.setText("Last Name");
        jPanel7.add(jLabel47);
        jLabel47.setBounds(352, 43, 98, 16);
        jPanel7.add(lnamebox1);
        lnamebox1.setBounds(496, 40, 155, 22);

        jLabel48.setText("Father's Name");
        jPanel7.add(jLabel48);
        jLabel48.setBounds(0, 71, 96, 16);
        jPanel7.add(fatherbox1);
        fatherbox1.setBounds(154, 71, 155, 22);

        jLabel49.setText("Mother's Name");
        jPanel7.add(jLabel49);
        jLabel49.setBounds(352, 74, 98, 16);
        jPanel7.add(motherbox1);
        motherbox1.setBounds(496, 71, 155, 22);

        jLabel50.setText("DOB");
        jPanel7.add(jLabel50);
        jLabel50.setBounds(0, 133, 96, 24);

        jLabel51.setText("Gender");
        jPanel7.add(jLabel51);
        jLabel51.setBounds(352, 134, 98, 23);

        malebtn1.setText("Male");
        jPanel7.add(malebtn1);
        malebtn1.setBounds(496, 134, 63, 25);

        femalebtn1.setText("Female");
        jPanel7.add(femalebtn1);
        femalebtn1.setBounds(561, 134, 90, 25);

        jLabel52.setText("Class");
        jPanel7.add(jLabel52);
        jLabel52.setBounds(0, 168, 96, 20);

        classbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class" }));
        classbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbox1ActionPerformed(evt);
            }
        });
        jPanel7.add(classbox1);
        classbox1.setBounds(154, 168, 155, 22);

        jLabel53.setText("Section");
        jPanel7.add(jLabel53);
        jLabel53.setBounds(352, 168, 98, 20);

        sectionbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section" }));
        sectionbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionbox2ActionPerformed(evt);
            }
        });
        jPanel7.add(sectionbox2);
        sectionbox2.setBounds(496, 168, 155, 22);

        imagebox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(imagebox1);
        imagebox1.setBounds(819, 49, 130, 130);

        jLabel54.setText("Phone Number");
        jPanel7.add(jLabel54);
        jLabel54.setBounds(0, 202, 96, 16);

        phonebox1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel7.add(phonebox1);
        phonebox1.setBounds(154, 199, 155, 22);

        jLabel55.setText("Landline Number");
        jPanel7.add(jLabel55);
        jLabel55.setBounds(0, 239, 96, 16);

        landlinebox1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel7.add(landlinebox1);
        landlinebox1.setBounds(154, 230, 155, 22);

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(154, 391, 121, 25);

        jLabel56.setText("Address");
        jPanel7.add(jLabel56);
        jLabel56.setBounds(0, 264, 93, 23);

        addressbox1.setColumns(20);
        addressbox1.setRows(5);
        addressbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addressbox1MouseExited(evt);
            }
        });
        addressbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressbox1KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(addressbox1);

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(154, 264, 458, 116);

        jLabel57.setText("Father's Occupation");
        jPanel7.add(jLabel57);
        jLabel57.setBounds(0, 102, 140, 20);

        foccubox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        jPanel7.add(foccubox1);
        foccubox1.setBounds(154, 102, 155, 22);

        moccubox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        jPanel7.add(moccubox1);
        moccubox1.setBounds(496, 102, 155, 22);

        jLabel58.setText("Mother's Occupation");
        jPanel7.add(jLabel58);
        jLabel58.setBounds(352, 102, 140, 20);

        jLabel59.setText("Blood Group");
        jPanel7.add(jLabel59);
        jLabel59.setBounds(352, 202, 98, 16);

        bgbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel7.add(bgbox1);
        bgbox1.setBounds(496, 199, 155, 22);

        jLabel60.setText("Religion");
        jPanel7.add(jLabel60);
        jLabel60.setBounds(352, 233, 98, 16);

        religionbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Religion", "Hindu", "Sikh", "Muslim", "Christian", "Jain", "Budhism", "Others" }));
        jPanel7.add(religionbox1);
        religionbox1.setBounds(500, 230, 150, 22);

        admbox2.setText("0");
        jPanel7.add(admbox2);
        admbox2.setBounds(154, 11, 90, 16);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(293, 391, 121, 25);

        jPanel8.setLayout(null);

        jLabel61.setText("Admission Number");
        jPanel8.add(jLabel61);
        jLabel61.setBounds(0, 11, 120, 16);

        jLabel63.setText("First Name");
        jPanel8.add(jLabel63);
        jLabel63.setBounds(0, 37, 96, 20);

        fnamebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamebox2ActionPerformed(evt);
            }
        });
        jPanel8.add(fnamebox2);
        fnamebox2.setBounds(154, 40, 155, 22);

        jLabel64.setText("Last Name");
        jPanel8.add(jLabel64);
        jLabel64.setBounds(352, 43, 98, 16);
        jPanel8.add(lnamebox2);
        lnamebox2.setBounds(496, 40, 155, 22);

        jLabel65.setText("Father's Name");
        jPanel8.add(jLabel65);
        jLabel65.setBounds(0, 71, 96, 16);
        jPanel8.add(fatherbox2);
        fatherbox2.setBounds(154, 71, 155, 22);

        jLabel66.setText("Mother's Name");
        jPanel8.add(jLabel66);
        jLabel66.setBounds(352, 74, 98, 16);
        jPanel8.add(motherbox2);
        motherbox2.setBounds(496, 71, 155, 22);

        jLabel68.setText("Gender");
        jPanel8.add(jLabel68);
        jLabel68.setBounds(350, 160, 98, 23);

        buttonGroup2.add(malebtn2);
        malebtn2.setText("Male");
        jPanel8.add(malebtn2);
        malebtn2.setBounds(500, 160, 63, 25);

        buttonGroup2.add(femalebtn2);
        femalebtn2.setText("Female");
        femalebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalebtn2ActionPerformed(evt);
            }
        });
        jPanel8.add(femalebtn2);
        femalebtn2.setBounds(570, 160, 90, 25);

        jLabel69.setText("Class");
        jPanel8.add(jLabel69);
        jLabel69.setBounds(0, 160, 96, 20);

        classbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        classbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbox2ActionPerformed(evt);
            }
        });
        jPanel8.add(classbox2);
        classbox2.setBounds(150, 160, 155, 22);

        jLabel70.setText("Section");
        jPanel8.add(jLabel70);
        jLabel70.setBounds(0, 200, 98, 20);

        sectionbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section", "A", "B", "C", "D" }));
        sectionbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionbox3ActionPerformed(evt);
            }
        });
        jPanel8.add(sectionbox3);
        sectionbox3.setBounds(150, 200, 155, 22);

        imagebox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(imagebox2);
        imagebox2.setBounds(819, 49, 130, 130);

        jLabel71.setText("Phone Number");
        jPanel8.add(jLabel71);
        jLabel71.setBounds(0, 240, 96, 16);

        phonebox2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel8.add(phonebox2);
        phonebox2.setBounds(150, 240, 155, 22);

        jLabel72.setText("Landline Number");
        jPanel8.add(jLabel72);
        jLabel72.setBounds(0, 290, 96, 16);

        landlinebox2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel8.add(landlinebox2);
        landlinebox2.setBounds(150, 290, 155, 22);

        jButton11.setText("Save");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11);
        jButton11.setBounds(160, 460, 121, 25);

        jLabel73.setText("Address");
        jPanel8.add(jLabel73);
        jLabel73.setBounds(0, 330, 93, 23);

        addressbox2.setColumns(20);
        addressbox2.setRows(5);
        addressbox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addressbox2MouseExited(evt);
            }
        });
        addressbox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressbox2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(addressbox2);

        jPanel8.add(jScrollPane4);
        jScrollPane4.setBounds(160, 330, 500, 116);

        jLabel74.setText("Father's Occupation");
        jPanel8.add(jLabel74);
        jLabel74.setBounds(0, 120, 140, 20);

        foccubox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        foccubox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foccubox2ActionPerformed(evt);
            }
        });
        jPanel8.add(foccubox2);
        foccubox2.setBounds(150, 120, 155, 22);

        moccubox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Occupation", "Business", "Service", "Self-employed", "House Maker" }));
        moccubox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moccubox2ActionPerformed(evt);
            }
        });
        jPanel8.add(moccubox2);
        moccubox2.setBounds(500, 120, 155, 22);

        jLabel75.setText("Mother's Occupation");
        jPanel8.add(jLabel75);
        jLabel75.setBounds(350, 120, 140, 20);

        jLabel76.setText("Blood Group");
        jPanel8.add(jLabel76);
        jLabel76.setBounds(350, 240, 98, 16);

        bgbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel8.add(bgbox2);
        bgbox2.setBounds(500, 240, 155, 22);

        jLabel77.setText("Religion");
        jPanel8.add(jLabel77);
        jLabel77.setBounds(350, 290, 98, 16);

        religionbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Religion", "Hindu", "Sikh", "Muslim", "Christian", "Jain", "Budhism", "Others" }));
        jPanel8.add(religionbox2);
        religionbox2.setBounds(500, 290, 155, 22);

        admbox3.setText("0");
        jPanel8.add(admbox3);
        admbox3.setBounds(154, 11, 90, 16);

        jButton13.setText("Delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);
        jButton13.setBounds(290, 460, 120, 25);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(adbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton6))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel25)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameboxActionPerformed

    private void classboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classboxActionPerformed

    }//GEN-LAST:event_classboxActionPerformed

    private void sectionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser myfilechooser = new JFileChooser();

        myfilechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }

                String extension = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                String allowed[] = {"jpg", "png", "gif", "jpeg"};
                for (String a : allowed) {
                    if (a.equalsIgnoreCase(extension)) {
                        return true;
                    } else {
                        return false;
                    }
                }
                return false;

            }

            @Override
            public String getDescription() {
                return "All Picture Files";

            }
        });

        if (myfilechooser.showOpenDialog(rootPane) == JFileChooser.APPROVE_OPTION) {
            myfile = myfilechooser.getSelectedFile();
            try {
                Image simg = ImageIO.read(new File(myfile.getAbsolutePath())).getScaledInstance(imagebox.getWidth(), imagebox.getHeight(), Image.SCALE_AREA_AVERAGING);
                imagebox.setIcon(new ImageIcon(simg));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Cannot read image");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String filename;
        if (myfile != null) {
            long timestamp = new java.util.Date().getTime();
            filename = timestamp + myfile.getName();
            try {
                FileInputStream fin = new FileInputStream(myfile.getAbsolutePath());
                FileOutputStream fout = new FileOutputStream("uploads//" + filename);
                int c;
                byte mybuffer[] = new byte[1024];
                while ((c = fin.read(mybuffer)) != -1) {

                    fout.write(mybuffer, 0, c);

                }
                fout.close();
                fin.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            filename = "no_image.png";
        }

        {
            try {
                String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);

                try {
                    
                    
                    
                    String a = "insert into studenttable(fname,lname,fathername,mothername,foccu,moccu,gender,class,section,phone,bloodgroup,landline,religion,address,studentimage) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement mystatement = myconnection.prepareStatement(a);
                  
                    mystatement.setString(1, fnamebox.getText());
                    mystatement.setString(2, lnamebox.getText());
                    mystatement.setString(3, fatherbox.getText());
                    mystatement.setString(4, motherbox.getText());
                    mystatement.setString(5, foccubox.getSelectedItem().toString());
                    mystatement.setString(6, moccubox.getSelectedItem().toString());

                    mystatement.setString(15, filename);
                    if (malebtn.isSelected()) {
                        mystatement.setString(7, "male");
                    } else if (femalebtn.isSelected()) {
                        mystatement.setString(7, "female");
                    }
                    mystatement.setString(8, classbox.getSelectedItem().toString());
                    mystatement.setString(9, sectionbox.getSelectedItem().toString());
                    mystatement.setString(10, phonebox.getText());
                    mystatement.setString(11, bgbox.getSelectedItem().toString());
                    mystatement.setString(12, landlinebox.getText());
                    mystatement.setString(13, religionbox.getSelectedItem().toString());
                    mystatement.setString(14, addressbox.getText());

                    if (mystatement.executeUpdate() > 0) {
                        fnamebox.setText("");
                        lnamebox.setText("");
                        fatherbox.setText("");
                        motherbox.setText("");
                        foccubox.setSelectedIndex(0);
                        moccubox.setSelectedIndex(0);

                        phonebox.setText("");
                        landlinebox.setText("");
                        addressbox.setText("");
                        bgbox.setSelectedIndex(0);
                        religionbox.setSelectedIndex(0);
                        
                        buttonGroup2.clearSelection();

                        classbox.setSelectedIndex(0);
                        sectionbox.setSelectedIndex(0);
                        imagebox.setIcon(null);
                        
                         try {
               

                Connection myconnection2 = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);
try{

String query="select * from studenttable";

 PreparedStatement mystatement2 = myconnection2.prepareStatement(query);
  ResultSet myresult2 = mystatement2.executeQuery();
  if(myresult2.next())
  {
      if(myresult2.last())
  {
admno=Integer.parseInt(myresult2.getString("admno"));
admdisplay=admno+1;

jLabel2.setText(String.valueOf(admdisplay));
  }
  }
}
     catch(Exception e){
         
         e.printStackTrace();
         
         
     }finally{
myconnection2.close();
}
         
         } catch(Exception e){
         e.printStackTrace();
         }  
                        
                        
                        JOptionPane.showMessageDialog(rootPane, "Student Data Saved Successfully");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error either due to admission number already exist/ fill all fields");
                } finally {
                    myconnection.close();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void addressboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressboxMouseExited
        jButton2.setEnabled(true);
    }//GEN-LAST:event_addressboxMouseExited

    private void addressboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressboxKeyPressed
        jButton2.setEnabled(true);
    }//GEN-LAST:event_addressboxKeyPressed

    private void adbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adbtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (adbtn.isSelected()) {
            try {
                String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);

                try {
                    String a = "select * from studenttable where admno=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(a);
                    mystatement.setString(1, search.getText());
                    ResultSet myresult = mystatement.executeQuery();
                    if (myresult.next()) {
                        jButton11.setEnabled(true);
                        jButton13.setEnabled(true);
                        admbox3.setText(myresult.getString("admno"));
                        fnamebox2.setText(myresult.getString("fname"));
                        lnamebox2.setText(myresult.getString("lname"));
                        fatherbox2.setText(myresult.getString("fathername"));
                        motherbox2.setText(myresult.getString("mothername"));
                        foccubox2.setSelectedItem(myresult.getString("foccu"));
                        moccubox2.setSelectedItem(myresult.getString("moccu"));

                        if (myresult.getString("gender").equals("male")) {
                            malebtn2.setSelected(true);
                        } else if (myresult.getString("gender").equals("female")) {
                            femalebtn2.setSelected(true);
                        }
                        classbox2.setSelectedItem(myresult.getString("class"));
                        sectionbox3.setSelectedItem(myresult.getString("section"));
                        phonebox2.setText(myresult.getString("phone"));
                        bgbox2.setSelectedItem(myresult.getString("bloodgroup"));
                        landlinebox2.setText(myresult.getString("landline"));
                        religionbox2.setSelectedItem(myresult.getString("religion"));
                        addressbox2.setText(myresult.getString("address"));
                        String myFile = myresult.getString("studentimage");
                        imagename2 = myFile;
                        Image simg = ImageIO.read(new File("uploads//" + myFile)).getScaledInstance(imagebox2.getWidth(), imagebox2.getHeight(), Image.SCALE_DEFAULT);
                        imagebox2.setIcon(new ImageIcon(simg));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Admission no. not found");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                } finally {
                    myconnection.close();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
        }
        if (nbtn.isSelected()) {
            try {
                String PATH = "jdbc:mysql://localhost/";
                String PLACE = "Schooldb";
                String USERNAME = "root";
                String PASSWORD = "";

                Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);

                try {
                    String a = "select * from studenttable where fname=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(a);
                    mystatement.setString(1, search.getText());
                    ResultSet myresult = mystatement.executeQuery();
                    if (myresult.next()) {
                        jButton11.setEnabled(true);
                        jButton13.setEnabled(true);
                        admbox3.setText(myresult.getString("admno"));
                        fnamebox2.setText(myresult.getString("fname"));
                        lnamebox2.setText(myresult.getString("lname"));
                        fatherbox2.setText(myresult.getString("fathername"));
                        motherbox2.setText(myresult.getString("mothername"));
                        foccubox2.setSelectedItem(myresult.getString("foccu"));
                        moccubox2.setSelectedItem(myresult.getString("moccu"));

                        if (myresult.getString("gender").equals("male")) {
                            malebtn2.setSelected(true);
                        } else if (myresult.getString("gender").equals("female")) {
                            femalebtn2.setSelected(true);
                        }
                        classbox2.setSelectedItem(myresult.getString("class"));
                        sectionbox3.setSelectedItem(myresult.getString("section"));
                        phonebox2.setText(myresult.getString("phone"));
                        bgbox2.setSelectedItem(myresult.getString("bloodgroup"));
                        landlinebox2.setText(myresult.getString("landline"));
                        religionbox2.setSelectedItem(myresult.getString("religion"));
                        addressbox2.setText(myresult.getString("address"));
                        String myFile = myresult.getString("studentimage");
                        imagename2 = myFile;
                        Image simg = ImageIO.read(new File("uploads//" + myFile)).getScaledInstance(imagebox2.getWidth(), imagebox2.getHeight(), Image.SCALE_DEFAULT);
                        imagebox2.setIcon(new ImageIcon(simg));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Name not found");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                } finally {
                    myconnection.close();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    }//GEN-LAST:event_jButton9ActionPerformed

    private void classbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classbox3ActionPerformed

    private void sectionbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionbox1ActionPerformed

    private void fnamebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamebox1ActionPerformed

    private void classbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classbox1ActionPerformed

    private void sectionbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionbox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void addressbox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressbox1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addressbox1MouseExited

    private void addressbox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressbox1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressbox1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void fnamebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamebox2ActionPerformed

    private void classbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classbox2ActionPerformed

    private void sectionbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionbox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionbox3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            String PATH = "jdbc:mysql://localhost/";
            String PLACE = "Schooldb";
            String USERNAME = "root";
            String PASSWORD = "";

            Connection myconnection = DriverManager.getConnection(PATH + PLACE, USERNAME, PASSWORD);
            try {
                String myquery = "update studenttable set fname=?, "
                        + "lname=?, fathername=?, mothername=?, foccu=?, moccu=?,  gender=?, class=?, section=?, phone=?, bloodgroup=?, landline=?, religion=?, address=?"
                        + "where admno=?";
                PreparedStatement mystatement = myconnection.prepareStatement(myquery);

                mystatement.setString(15, admbox3.getText());
                mystatement.setString(1, fnamebox2.getText());
                mystatement.setString(2, lnamebox2.getText());
                mystatement.setString(3, fatherbox2.getText());
                mystatement.setString(4, motherbox2.getText());
                mystatement.setString(5, foccubox2.getSelectedItem().toString());
                mystatement.setString(6, moccubox2.getSelectedItem().toString());
                

                if (malebtn2.isSelected()) {
                    mystatement.setString(7, "male");
                } else if (femalebtn2.isSelected()) {
                    mystatement.setString(7, "female");
                }
                mystatement.setString(8, classbox2.getSelectedItem().toString());
                mystatement.setString(9, sectionbox3.getSelectedItem().toString());
                mystatement.setString(10, phonebox2.getText());
                mystatement.setString(11, bgbox2.getSelectedItem().toString());
                mystatement.setString(12, landlinebox2.getText());
                mystatement.setString(13, religionbox2.getSelectedItem().toString());
                mystatement.setString(14, addressbox2.getText());

                if (mystatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Updated Successfully");
                    fnamebox2.setText("");
                    lnamebox2.setText("");
                    fatherbox2.setText("");
                    motherbox2.setText("");
                    foccubox2.setSelectedIndex(0);
                    moccubox2.setSelectedIndex(0);
                    search.setText("");
                    phonebox2.setText("");
                    landlinebox2.setText("");
                    addressbox2.setText("");
                    bgbox2.setSelectedIndex(0);
                    religionbox2.setSelectedIndex(0);
                    buttonGroup2.clearSelection();
                    admbox3.setText("0");
                    classbox2.setSelectedIndex(0);
                    sectionbox3.setSelectedIndex(0);
                    imagebox2.setIcon(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Sorry, some problem occured");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
            } finally {
                myconnection.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void addressbox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressbox2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addressbox2MouseExited

    private void addressbox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressbox2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressbox2KeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        int answer=JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if(answer==JOptionPane.YES_OPTION)
                {
                    try{
                    
                    File myfile=new File("uploads//"+imagename2);
                    myfile.delete();
                    

       
             String PATH="jdbc:mysql://localhost/";
             String PLACE="Schooldb";
             String USERNAME="root";
             String PASSWORD="";
                

             Connection   myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try {
                String a = "delete from studenttable where admno=?";
                PreparedStatement mystatement = myconnection.prepareStatement(a);

                mystatement.setString(1, admbox3.getText());

                    if (mystatement.executeUpdate()>0) {
                        JOptionPane.showMessageDialog(rootPane, "Student Data Deleted Successfully ");
                        fnamebox2.setText("");
                    lnamebox2.setText("");
                    fatherbox2.setText("");
                    motherbox2.setText("");
                    foccubox2.setSelectedIndex(0);
                    moccubox2.setSelectedIndex(0);
                    search.setText("");
                    phonebox2.setText("");
                    landlinebox2.setText("");
                    addressbox2.setText("");
                    bgbox2.setSelectedIndex(0);
                    religionbox2.setSelectedIndex(0);
                    buttonGroup2.clearSelection();
                    admbox3.setText("0");
                    classbox2.setSelectedIndex(0);
                    sectionbox3.setSelectedIndex(0);
                    imagebox2.setIcon(null);

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Error in Saving Successfully ");
                    }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            } finally {
                myconnection.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
                }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void foccubox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foccubox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foccubox2ActionPerformed

    private void moccubox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moccubox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moccubox2ActionPerformed

    private void femalebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalebtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalebtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adbox;
    private javax.swing.JRadioButton adbtn;
    private javax.swing.JTextArea address;
    private javax.swing.JTextArea addressbox;
    private javax.swing.JTextArea addressbox1;
    private javax.swing.JTextArea addressbox2;
    private javax.swing.JFormattedTextField admbox1;
    private javax.swing.JLabel admbox2;
    private javax.swing.JLabel admbox3;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.JComboBox<String> bgbox;
    private javax.swing.JComboBox<String> bgbox1;
    private javax.swing.JComboBox<String> bgbox2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> classbox;
    private javax.swing.JComboBox<String> classbox1;
    public static javax.swing.JComboBox<String> classbox2;
    private javax.swing.JComboBox<String> classbox3;
    private javax.swing.JTextField fatherbox;
    private javax.swing.JTextField fatherbox1;
    private javax.swing.JTextField fatherbox2;
    private javax.swing.JTextField fathername;
    private javax.swing.JRadioButton female;
    private javax.swing.JRadioButton femalebtn;
    private javax.swing.JRadioButton femalebtn1;
    private javax.swing.JRadioButton femalebtn2;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JTextField fnamebox1;
    private javax.swing.JTextField fnamebox2;
    private javax.swing.JComboBox<String> foccu;
    private javax.swing.JComboBox<String> foccubox;
    private javax.swing.JComboBox<String> foccubox1;
    private javax.swing.JComboBox<String> foccubox2;
    private javax.swing.JLabel ibox;
    private javax.swing.JLabel imagebox;
    private javax.swing.JLabel imagebox1;
    private javax.swing.JLabel imagebox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField landline;
    private javax.swing.JFormattedTextField landlinebox;
    private javax.swing.JFormattedTextField landlinebox1;
    private javax.swing.JFormattedTextField landlinebox2;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JTextField lnamebox1;
    private javax.swing.JTextField lnamebox2;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton malebtn;
    private javax.swing.JRadioButton malebtn1;
    private javax.swing.JRadioButton malebtn2;
    private javax.swing.JComboBox<String> moccu;
    private javax.swing.JComboBox<String> moccubox;
    private javax.swing.JComboBox<String> moccubox1;
    private javax.swing.JComboBox<String> moccubox2;
    private javax.swing.JTextField motherbox;
    private javax.swing.JTextField motherbox1;
    private javax.swing.JTextField motherbox2;
    private javax.swing.JTextField mothername;
    private javax.swing.JRadioButton nbtn;
    private javax.swing.JFormattedTextField phone;
    private javax.swing.JFormattedTextField phonebox;
    private javax.swing.JFormattedTextField phonebox1;
    private javax.swing.JFormattedTextField phonebox2;
    private javax.swing.JComboBox<String> religion;
    private javax.swing.JComboBox<String> religionbox;
    private javax.swing.JComboBox<String> religionbox1;
    private javax.swing.JComboBox<String> religionbox2;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> sectionbox;
    private javax.swing.JComboBox<String> sectionbox1;
    private javax.swing.JComboBox<String> sectionbox2;
    private javax.swing.JComboBox<String> sectionbox3;
    // End of variables declaration//GEN-END:variables
}
